In [1]:
import pandas as pd

In [2]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [3]:
documents[0]

{'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
 'section': 'General course-related questions',
 'question': 'Course - When will the course start?',
 'course': 'data-engineering-zoomcamp'}

In [4]:
df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])

In [5]:
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [6]:
df.tail()

course                   section  \
943  mlops-zoomcamp  Module 6: Best practices   
944  mlops-zoomcamp  Module 6: Best practices   
945  mlops-zoomcamp  Module 6: Best practices   
946  mlops-zoomcamp  Module 6: Best practices   
947  mlops-zoomcamp  Module 6: Best practices   

                                              question  \
943  Github actions: Permission denied error when e...   
944  Managing Multiple Docker Containers with docke...   
945           AWS regions need to match docker-compose   
946                                   Isort Pre-commit   
947  How to destroy infrastructure created via GitH...   

                                                  text  
943  Problem description\nThis is the step in the c...  
944  Problem description\nWhen a docker-compose fil...  
945  Problem description\nIf you are having problem...  
946  Problem description\nPre-commit command was fa...  
947  Problem description\nInfrastructure created in...

In [7]:
df[df.course == 'data-engineering-zoomcamp']

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
3    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
..                         ...                               ...   
430  data-engineering-zoomcamp           Workshop 2 - RisingWave   
431  data-engineering-zoomcamp           Workshop 2 - RisingWave   
432  data-engineering-zoomcamp           Workshop 2 - RisingWave   
433  data-engineering-zoomcamp          Triggers in Mage via CLI   
434  data-engineering-zoomcamp          Triggers in Mage via CLI   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
2    Course - Can I still join the course after the...   
3    Course - I have registered for the Data Engine...   
4     Course - What can I do before the course starts?   
..                                                 ...   
430  Unable to Open Dashboard as xdg-open doesn’t o...   
431  Resolving Python Interpreter Path Inconsistenc...   
432                    How does windowing work in Sql?   
433  Encountering the error "ModuleNotFoundError: N...   
434                                     Basic Commands   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
2    Yes, even if you don't register, you're still ...  
3    You don't need it. You're accepted. You can al...  
4    You can start by installing and setting up all...  
..                                                 ...  
430  Refer to the solution given in the first solut...  
431  Example Error:\nWhen attempting to execute a P...  
432  Ans : Windowing in streaming SQL involves defi...  
433  Python 3.12.1, is not compatible with kafka-py...  
434  Docker Commands\n# Create a Docker Image from ...  

[435 rows x 4 columns]

In [8]:
df

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
3    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
..                         ...                               ...   
943             mlops-zoomcamp          Module 6: Best practices   
944             mlops-zoomcamp          Module 6: Best practices   
945             mlops-zoomcamp          Module 6: Best practices   
946             mlops-zoomcamp          Module 6: Best practices   
947             mlops-zoomcamp          Module 6: Best practices   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
2    Course - Can I still join the course after the...   
3    Course - I have registered for the Data Engine...   
4     Course - What can I do before the course starts?   
..                                                 ...   
943  Github actions: Permission denied error when e...   
944  Managing Multiple Docker Containers with docke...   
945           AWS regions need to match docker-compose   
946                                   Isort Pre-commit   
947  How to destroy infrastructure created via GitH...   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
2    Yes, even if you don't register, you're still ...  
3    You don't need it. You're accepted. You can al...  
4    You can start by installing and setting up all...  
..                                                 ...  
943  Problem description\nThis is the step in the c...  
944  Problem description\nWhen a docker-compose fil...  
945  Problem description\nIf you are having problem...  
946  Problem description\nPre-commit command was fa...  
947  Problem description\nInfrastructure created in...  

[948 rows x 4 columns]

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cv = CountVectorizer(min_df=5)

In [11]:
cv.fit(df.text)

CountVectorizer(min_df=5)

In [12]:
cv.get_feature_names_out()

array(['01', '02', '03', ..., 'youtube', 'zip', 'zoomcamp'],
      shape=(1524,), dtype=object)

In [13]:
doc_examples = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [14]:
cv = CountVectorizer(stop_words="english")

In [15]:
cv.fit(doc_examples)

CountVectorizer(stop_words='english')

In [16]:
cv.get_feature_names_out()

array(['15th', '2024', 'cloud', 'course', 'date', 'github', 'google',
       'homeworks', 'jan', 'listed', 'participation', 'prerequisites',
       'python', 'registration', 'required', 'setup', 'start', 'starts',
       'submit'], dtype=object)

In [17]:
X = cv.transform(doc_examples)

In [18]:
pd.DataFrame(X.todense(), columns = cv.get_feature_names_out()).T

0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs.round(2)

0     1     2    3    4     5     6    7     8     9    ...  938  \
01        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
02        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
03        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
04        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
05        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
...       ...   ...   ...  ...  ...   ...   ...  ...   ...   ...  ...  ...   
yes       0.0  0.00  0.28  0.0  0.0  0.00  0.21  0.2  0.15  0.00  ...  0.0   
yml       0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
youtube   0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.15  ...  0.0   
zip       0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
zoomcamp  0.0  0.43  0.00  0.0  0.0  0.19  0.00  0.0  0.00  0.00  ...  0.0   

          939  940  941  942   943  944  945  946   947  
01        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
02        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
03        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
04        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
05        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
...       ...  ...  ...  ...   ...  ...  ...  ...   ...  
yes       0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
yml       0.0  0.0  0.0  0.0  0.11  0.0  0.0  0.0  0.00  
youtube   0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
zip       0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
zoomcamp  0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.15  

[1333 rows x 948 columns]

In [20]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23808 stored elements and shape (948, 1333)>

In [21]:
query = "I just discovered the course. Is it too late to join?"

q = cv.transform([query])
pd.DataFrame(q.toarray(), columns=cv.get_feature_names_out()).T

0
01        0.0
02        0.0
03        0.0
04        0.0
05        0.0
...       ...
yes       0.0
yml       0.0
youtube   0.0
zip       0.0
zoomcamp  0.0

[1333 rows x 1 columns]

In [22]:
query_dict = dict(zip(names, q.toarray()[0]))
#[print(k, v) for k, v in query_dict.items() if v > 0]
#list(filter(lambda x: x > 0, [v for k, v in query_dict.items()]))

In [23]:
doc_dict = dict(zip(names, X.toarray()[2]))
#[print(k, v) for k, v in doc_dict.items() if v > 0]

In [24]:
X.dot(q.T).todense()

matrix([[0.48049682],
        [0.        ],
        [0.        ],
        [0.2083882 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.17557272],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.15870689],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.09680922],
        [0.        ],
        [0.        ],
        [0.07529201],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.29986763],
        [0.10520675],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.27447476],
        [0.12828407],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05163407],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.03156309],
        [0.04914818],
        [0.07138962],
        [0.        ],
        [0.04329773],
        [0.        ],
        [0

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
score = cosine_similarity(X, q).flatten()

In [27]:
import numpy as np

In [28]:
np.argsort(score)[-5:]

array([ 22, 448, 449, 440,   0])

In [29]:
df.iloc[449].text

'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'

In [30]:
df

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
3    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
..                         ...                               ...   
943             mlops-zoomcamp          Module 6: Best practices   
944             mlops-zoomcamp          Module 6: Best practices   
945             mlops-zoomcamp          Module 6: Best practices   
946             mlops-zoomcamp          Module 6: Best practices   
947             mlops-zoomcamp          Module 6: Best practices   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
2    Course - Can I still join the course after the...   
3    Course - I have registered for the Data Engine...   
4     Course - What can I do before the course starts?   
..                                                 ...   
943  Github actions: Permission denied error when e...   
944  Managing Multiple Docker Containers with docke...   
945           AWS regions need to match docker-compose   
946                                   Isort Pre-commit   
947  How to destroy infrastructure created via GitH...   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
2    Yes, even if you don't register, you're still ...  
3    You don't need it. You're accepted. You can al...  
4    You can start by installing and setting up all...  
..                                                 ...  
943  Problem description\nThis is the step in the c...  
944  Problem description\nWhen a docker-compose fil...  
945  Problem description\nIf you are having problem...  
946  Problem description\nPre-commit command was fa...  
947  Problem description\nInfrastructure created in...  

[948 rows x 4 columns]

In [31]:
fields = ['section', 'question', 'text']

In [32]:
matrices = {}
vectorizers = {}

for f in fields:
    cv = TfidfVectorizer()
    X = cv.fit_transform(df[f])
    matrices[f] = X
    vectorizers[f] = cv

In [33]:
matrices

{'section': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 3651 stored elements and shape (948, 86)>,
 'question': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 8938 stored elements and shape (948, 2051)>,
 'text': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 47683 stored elements and shape (948, 6711)>}

In [34]:
vectorizers

{'section': TfidfVectorizer(),
 'question': TfidfVectorizer(),
 'text': TfidfVectorizer()}

In [35]:
n = len(df)

In [36]:
n

948

In [37]:
score = np.zeros(n)
query = 'I just signed up. Is it too late to join the course?'

boosts = {
    'question': 3.0
}

for f in fields:
    q = vectorizers[f].transform([query])
    X = matrices[f]

    f_score = cosine_similarity(X, q).flatten()

    boost = boosts.get(f, 1.0)

    score = score + boost * f_score



In [38]:
score

array([1.14094558, 0.81596966, 1.33056267, 0.65732068, 0.83576004,
       0.52476342, 0.66858864, 1.0787197 , 0.74706959, 0.55772975,
       0.68656319, 0.56112268, 0.53336373, 0.43478918, 0.27432056,
       0.95629274, 0.48958677, 0.68492481, 0.3829383 , 0.49858614,
       0.29339573, 0.47971766, 0.48682824, 0.32341637, 0.34790387,
       0.26031374, 0.23246462, 0.67339941, 0.40084129, 0.37116011,
       0.35832744, 0.49357393, 0.23246462, 0.81793683, 0.77687713,
       0.74140289, 0.2468553 , 0.23886212, 0.45739604, 0.41766658,
       0.3907986 , 0.61285357, 0.2384047 , 0.26177404, 0.26613661,
       0.13144557, 0.        , 0.03763082, 0.1684484 , 0.01471408,
       0.01769699, 0.08498023, 0.20756067, 0.17251289, 0.04697298,
       0.09783391, 0.14133976, 0.11178007, 0.09787604, 0.20922613,
       0.00892879, 0.22877672, 0.39785787, 0.03006711, 0.02359607,
       0.01409061, 0.01477017, 0.04512332, 0.01319535, 0.05420395,
       0.12621362, 0.00783901, 0.21820824, 0.03212773, 0.04674

In [39]:
filters = {
    'course': 'data-engineering-zoomcamp'
}

for field, value in filters.items():
    mask = (df[field] == value).astype(int)
    score = score * mask
mask
score

0      1.140946
1      0.815970
2      1.330563
3      0.657321
4      0.835760
         ...   
943    0.000000
944    0.000000
945    0.000000
946    0.000000
947    0.000000
Name: course, Length: 948, dtype: float64

In [40]:
idx = np.argsort(-score)[:5]

In [41]:
idx

0     2
1     0
2     7
3    15
4     4
Name: course, dtype: int64

In [42]:
df.iloc[idx]

course                           section  \
2   data-engineering-zoomcamp  General course-related questions   
0   data-engineering-zoomcamp  General course-related questions   
7   data-engineering-zoomcamp  General course-related questions   
15  data-engineering-zoomcamp  General course-related questions   
4   data-engineering-zoomcamp  General course-related questions   

                                             question  \
2   Course - Can I still join the course after the...   
0                Course - When will the course start?   
7   Course - Can I follow the course after it fini...   
15  Homework - Are late submissions of homework al...   
4    Course - What can I do before the course starts?   

                                                 text  
2   Yes, even if you don't register, you're still ...  
0   The purpose of this document is to capture fre...  
7   Yes, we will keep all the materials after the ...  
15  No, late submissions are not allowed. But if t...  
4   You can start by installing and setting up all...

In [43]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [44]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just signed up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

In [45]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 47683 stored elements and shape (948, 6711)>

In [46]:
from sklearn.decomposition import TruncatedSVD

X = matrices['text']
cv = vectorizers['text']

svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

X_emb[0]

array([ 0.26785234, -0.10688809, -0.02674629, -0.09302563, -0.05121219,
        0.09426828,  0.07327132,  0.04719641,  0.03966968, -0.04490591,
        0.07580735,  0.22967184, -0.13272319, -0.07275908, -0.04594044,
       -0.05648179])

In [47]:
cv

TfidfVectorizer()

In [48]:
X.shape
X_emb.shape

(948, 16)

In [49]:
query = 'I just signed up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.14032584, -0.0337391 , -0.02812477, -0.05821475, -0.00161476,
        0.07512659,  0.04250644,  0.02729788,  0.01900462, -0.00814365,
        0.01869215,  0.08035963, -0.04626542, -0.02141435, -0.04219334,
       -0.01577042])

In [50]:
np.dot(X_emb[0], Q_emb[0])

np.float64(0.09044888017176592)

In [51]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
list(df.loc[idx].text)

['No, late submissions are not allowed. But if the form is still not closed and it’s after the due date, you can still submit the homework. confirm your submission by the date-timestamp on the Course page.y\nOlder news:[source1] [source2]',
 'Yes, the slack channel remains open and you can ask questions there. But always sDocker containers exit code w search the channel first and second, check the FAQ (this document), most likely all your questions are already answered here.\nYou can also tag the bot @ZoomcampQABot to help you conduct the search, but don’t rely on its answers 100%, it is pretty good though.',
 "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with annou

In [52]:
df.loc[idx]

course                           section  \
15   data-engineering-zoomcamp  General course-related questions   
8    data-engineering-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
12   data-engineering-zoomcamp  General course-related questions   
451  machine-learning-zoomcamp  General course-related questions   
450  machine-learning-zoomcamp  General course-related questions   
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
2    data-engineering-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   

                                              question  \
15   Homework - Are late submissions of homework al...   
8    Course - Can I get support if I take the cours...   
0                 Course - When will the course start?   
12   Office Hours - What is the video/zoom link to ...   
451      Can I submit the homework after the due date?   
450                When does the next iteration start?   
764  What If I submitted only two projects and fail...   
2    Course - Can I still join the course after the...   
11   Certificate - Can I follow the course in a sel...   
436                      Is it going to be live? When?   

                                                  text  
15   No, late submissions are not allowed. But if t...  
8    Yes, the slack channel remains open and you ca...  
0    The purpose of this document is to capture fre...  
12   The zoom link is only published to instructors...  
451  No, it’s not possible. The form is closed afte...  
450  The course is available in the self-paced mode...  
764  If you have submitted two projects (and peer-r...  
2    Yes, even if you don't register, you're still ...  
11   No, you can only get a certificate if you fini...  
436  The course videos are pre-recorded, you can st...

In [53]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([0.06446791, 0.00035082, 0.02932362, 0.        , 0.07151602,
       0.        , 0.00215551, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.00530941, 0.        , 0.        ,
       0.        ])

In [54]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.04766356, 0.00952768, 0.00370339, 0.        , 0.02659088,
       0.        , 0.00094405, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [55]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

course                                   section  \
404  data-engineering-zoomcamp                                   Project   
29   data-engineering-zoomcamp          General course-related questions   
292  data-engineering-zoomcamp  Module 4: analytics engineering with dbt   
27   data-engineering-zoomcamp          General course-related questions   
768  machine-learning-zoomcamp                             Miscellaneous   
456  machine-learning-zoomcamp          General course-related questions   
39   data-engineering-zoomcamp          General course-related questions   
40   data-engineering-zoomcamp          General course-related questions   
2    data-engineering-zoomcamp          General course-related questions   
15   data-engineering-zoomcamp          General course-related questions   

                                              question  \
404               Project evaluation - Reproducibility   
29   Besides the “Office Hour” which are the live z...   
292  Not able to change Environment Type as it is g...   
27   Environment - The GCP and other cloud provider...   
768  Do you pass a project based on the average of ...   
456                Submitting learning in public links   
39                          How to troubleshoot issues   
40                                How to ask questions   
2    Course - Can I still join the course after the...   
15   Homework - Are late submissions of homework al...   

                                                  text  
404  The slack thread : thttps://datatalks-club.sla...  
29   We will probably have some calls during the Ca...  
292  You don't need to change the environment type....  
27   You can do most of the course without a cloud....  
768  Alexey Grigorev: “It’s based on all the scores...  
456  When you post about what you learned from the ...  
39   The first step is to try to solve the issue on...  
40   When the troubleshooting guide above does not ...  
2    Yes, even if you don't register, you're still ...  
15   No, late submissions are not allowed. But if t...

In [64]:
import torch
from transformers import BertModel, BertTokenizer

from transformers import AutoTokenizer

# Load BERT tokenizer
#model_name = "https://huggingface.co/google-bert/bert-base-uncased"
#tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load model directly
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")
model = AutoModelForMaskedLM.from_pretrained("google-bert/bert-base-uncased")
model.eval()  # Set the model to evaluation mode if not training

OSError: We couldn't connect to 'https://huggingface.co' to load the files, and couldn't find them in the cached files.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.